name: Curvenote Deploy
author: Curvenote
description: Deploy a Curvenote website to curve.space hosting
branding:
  icon: "zap"
  color: "blue"
inputs:
  pull:
    description: "pull latest changes from projects on curvenote.com during deployment"
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: "Checkout ${{github.ref}} branch"
      uses: actions/checkout@v3
    - name: Install the curvenote cli
      run: npm install -g curvenote
      shell: bash
    - name: Check curvenote version
      run: curvenote -v
      shell: bash
    - name: Confirm valid API token
      run: curvenote auth list
      shell: bash
    - name: Pull latest content
      if: ${{ inputs.pull == true }}
      run: curvenote pull -y
      shell: bash
    - name: Deploy the site
      run: curvenote deploy -y
      shell: bash
